{
 "title": "Quality Squad",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "squad",
    "label": "Squad",
    "query": "select distinct(squad) from jira_issue"
   }
  ]
 },
 "panels": [
  {
   "title": "General indicators (for all sprints and all bug phases)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "squad"
  },
  {
   "title": "Quantidade PBIs",
   "type": "stat",
   "description": "Closed bugs (status = 'Done') are considered in the last sprint in which they appear.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_lastSprint",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(issueName) from jira_issue where squad=~ /^(${squad})$/ ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lead Time AVG",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "repeat": "sprint",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(leadTimeTotal)  FROM jira_issue where leadTimeTotal > 0 AND squad =~ /^(${squad})$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lead Time Worst Case",
   "type": "stat",
   "description": "Considered the average time worked for all bugs that are 'Done'",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(leadTimeTotal)  FROM jira_issue where leadTimeTotal > 0 AND squad =~ /^(${squad})$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lead Time Transition Track",
   "type": "bargauge",
   "description": "Squad of all bugs for all sprints of all phases",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(leadTimeAnalise) as \"Análise\", mean(leadTimeReadyDiscover) as \"Pronto Descoberta\", mean(leadTimeBacklog) as \"Backlog\",mean(leadTimeDiscover) as \"Descoberta\", mean(leadTimeReadyDevelop) as \"Pronto Desenv\",mean(leadTimeDevelop) as \"Desenvolvimento\",mean(leadTimeDevelopDone) as \"Desenv Concluido\",mean(leadTimeSitUatRegress) as \"SIT UAT Regressivo\",\nmean(leadTimeReadyImplement) as \"Pronto Implantação\",mean(leadTimePilot) as \"Piloto\",mean(leadTimeDone) as \"Concluido\" FROM jira_issue where squad=~ /^(${squad})$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dataset from this dashboard (for all sprints and all bug phases)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 322 }
  },
  {
   "title": "Dataset",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 323 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT * from jira_issue",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}